// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package define

// Fill with you ideas below.

//type MessageNotifyResp struct {
//	MessageId int         `orm:"message_id,primary" json:"messageId"` // id
//	SenderId  int         `orm:"sender_id" json:"senderId"`           // 发送者id
//	Content   string      `orm:"content" json:"content"`              // 消息内容
//	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"`         // 创建时间
//}
