// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package define

// Fill with you ideas below.

type UpdateUserInfoReq struct {
	Email        string `orm:"email"           json:"email"`    // 邮箱，限30字
	UserNum      string `orm:"user_num"        json:"userNum"`  // 学号/职工号，限20位
	Username     string `orm:"username"        json:"username"` // 真实姓名，限6字
	Grade        int    `orm:"grade"           json:"grade"`    // 年级
	School       string `orm:"school"          json:"school"`   // 学院
	OldPassword  string
	Password     string `orm:"password"        json:"password"`     // 密码
	AvatarUrl    string `orm:"avatar_url"      json:"avatarUrl"`    // 头像url
	Gender       int    `orm:"gender"          json:"gender"`       // 性别
	Major        string `orm:"major"           json:"major"`        // 专业，限15字
	Organization string `orm:"organization"    json:"organization"` // 单位，例如计算机学院，限15字
	VerCode      string
}

type GetUserInfoResp struct {
	UserId       int    `orm:"user_id,primary" json:"userId"`       // 主键
	Email        string `orm:"email"           json:"email"`        // 邮箱
	UserNum      string `orm:"user_num"        json:"userNum"`      // 学号/职工号
	Username     string `orm:"username"        json:"username"`     // 真实姓名
	Grade        int    `orm:"grade"           json:"grade"`        // 年级
	School       string `orm:"school"          json:"school"`       // 学院
	AvatarUrl    string `orm:"avatar_url"      json:"avatarUrl"`    // 头像url
	Gender       int    `orm:"gender"          json:"gender"`       // 性别
	Major        string `orm:"major"           json:"major"`        // 专业
	Organization string `orm:"organization"    json:"organization"` // 单位，例如软件工程4班
	RoleId       int    `orm:"role_id"         json:"roleId"`       // 角色id
}

type ListCodingTimeByUserIdReq struct {
	UserId    int
	BeginDate string
	EndDate   string
}

//type LoginReq struct {
//	Passport string `valid:"required|email#登录名不能为空|登录名不为邮箱"` // 登陆凭证，目前是email
//	Password string `valid:"required|#登陆密码不能为空"`             // 密码
//}
//
//type RegisterReq struct {
//	Email    string `valid:"email#登录名不符合邮箱格式"`        // 登陆凭证，目前是email
//	Password string `valid:"password|#密码长度需在在6~18之间"` // 密码
//	Username string
//	VerCode  string
//}
//
//type UserUpdateReq struct {
//	Email        *string `orm:"email"           json:"email"`        // 邮箱，限30字
//	UserNum      *string `orm:"user_num"        json:"userNum"`      // 学号/职工号，限20位
//	Username     *string `orm:"username"        json:"username"`     // 真实姓名，限10字
//	Password     *string `orm:"password"        json:"password"`     // 密码
//	AvatarUrl    *string `orm:"avatar_url"      json:"avatarUrl"`    // 头像url
//	Gender       *int    `orm:"gender"          json:"gender"`       // 性别
//	Major        *string `orm:"major"           json:"major"`        // 专业，限15字
//	Organization *string `orm:"organization"    json:"organization"` // 单位，例如计算机学院，限15字
//	VerCode      string
//}
//
//type ResetPasswordReq struct {
//	Email    string // 邮箱
//	Password string // 密码
//	VerCode  string // 验证码
//}
//
//// DeleteUserReq 注销用户请求参数
//type DeleteUserReq struct {
//	Password string // 密码
//}
//
//type SysUserResp struct {
//	gmeta.Meta   `orm:"table:sys_user"`
//	UserId       int    `orm:"user_id,primary" json:"userId"`       // 主键
//	Email        string `orm:"email"           json:"email"`        // 邮箱，限30字
//	UserNum      string `orm:"user_num"        json:"userNum"`      // 学号/职工号，限20位
//	Username     string `orm:"username"        json:"username"`     // 真实姓名，限6字
//	Gender       int    `orm:"gender"          json:"gender"`       // 性别
//	Major        string `orm:"major"           json:"major"`        // 专业，限15字
//	Organization string `orm:"organization"    json:"organization"` // 单位，例如计算机学院，限15字
//	RoleId       int    `orm:"role_id"         json:"roleId"`       // 角色id
//	RoleDetail   struct {
//		gmeta.Meta  `orm:"table:sys_role"`
//		RoleId      int    `orm:"role_id,primary" json:"role_id"`
//		Description string `orm:"description" json:"description"`
//	} `orm:"with:role_id" json:"role_detail"` // 角色信息
//	UpdatedAt *gtime.Time `orm:"updated_at"      json:"updatedAt"` // 修改时间
//	CreatedAt *gtime.Time `orm:"created_at"      json:"createdAt"` // 创建时间
//}
