# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gf-app/server"
    IsMultiple  = false
    RealAddress = ":8199"

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

[gfcli]
    [gfcli.build]
        name     = "main"
        arch     = "amd64"
        system   = "linux"
        cgo      = 0
    [gfcli.gen.dao]
        link = "mysql:horace:scipio1322?@tcp(localhost:3306)/scnu_coding"
        prefix = ""
[minio]
    endpoint = "localhost:9000"
    accessKeyId = "admin"
    secretAccessKey = "admin123"
    bucketName = "scnu-coding"
    location = "cn-north-1"

[redis]
    default = "localhost:6379,0,scipio1322?"

[ide]
    # 目前只有两种方式，docker，k3s
    deploymentType = "docker"
    # docker运行的主机
    [ide.deployment.docker]
        host = "localhost"
        user = "horace"
        pass = "scipio"
    # k3s master主机
    [ide.deployment.k3s]
        host = "93.179.125.223:27196"
        user = "root"
        pass = "TefmYnzGKFVa"
    [ide.deployment.swarm]
        host = "93.179.125.223:27196"
        user = "root"
        pass = "TefmYnzGKFVa"
    # 代码存储的主机，如果是docker环境
    [ide.storage]
        host = "localhost"
        user = "horace"
        pass = "scipio"
        workspaceBasePathRemote = "/mnt/code-platform"
        workspaceBasePathLocal = ""
    [ide.config]
        chartName = ""
        # 带单位
        memoryLimit = "500m"
    [ide.image.name]
        cpp = "registry.cn-hangzhou.aliyuncs.com/jhchen/theia-cpp:0.04"
        java = "theiaide/theia-java:latest"
        python = "theiaide/theia-python:latest"
        go = "registry.cn-hangzhou.aliyuncs.com/jhchen/theia-go:latest"
        php = "registry.cn-hangzhou.aliyuncs.com/jhchen/theia-php:latest"
        swift = "registry.cn-hangzhou.aliyuncs.com/jhchen/theia-swift:latest"
        full = "theiaide/theia-full:latest"
        web = "theiaide/theia:latest"
    [ide.helm]
        chartName = ""
#    [ide.docker]
#        #运行的主机
#        user = "root"
#        host = "93.179.125.223:27196"
#        pass = "TefmYnzGKFVa"

# Database.
[database]
    link  = "mysql:horace:scipio1322?@tcp(localhost:3306)/scnu_coding"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true