# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gf-app/server"
    IsMultiple  = false

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

[gfcli]
    [gfcli.build]
        name     = "main"
        arch     = "amd64"
        system   = "linux"
        cgo      = 0
    [gfcli.gen.dao]
        link = "mysql:root:12345678@tcp(localhost:3306)/scnu_coding"
        prefix = ""
        tables = "local_file,sys_role,re_course_user,re_api_role,re_user_role,log,message_notify,coding_time,course_announcement,checkin_detail,checkin_record,lab,lab_comment,course,course_comment,lab_submit,sys_user"
[minio]
    endpoint = "localhost:9000"
    accessKeyID = "root"
    secretAccessKey = "12345678"

[redis]
    default = "localhost:6379,0,123456"

[ide]
    # 目前只有两种方式，docker，k3s
    deploymentType = "docker"
    # docker运行的主机
    [ide.deployment.docker]
        host = "93.179.125.223:27196"
        user = "root"
        pass = "TefmYnzGKFVa"
    # k3s master主机
    [ide.deployment.k3s]
        host = "93.179.125.223:27196"
        user = "root"
        pass = "TefmYnzGKFVa"
    [ide.image]
        chartName = ""
        # 带单位
        memoryLimit = "500m"
    [ide.image.name]
        cpp = "theiaide/theia-cpp:latest"
        java = "theiaide/theia-java:latest"
        python = "theiaide/theia-python:latest"
        go = "registry.cn-hangzhou.aliyuncs.com/jhchen/theia-go:latest"
        php = "registry.cn-hangzhou.aliyuncs.com/jhchen/theia-php:latest"
        swift = "registry.cn-hangzhou.aliyuncs.com/jhchen/theia-swift:latest"
        full = "theiaide/theia-full:latest"
        web = "theiaide/theia:latest"
    [ide.helm]
        chartName = ""
    [ide.docker]
        #运行的主机
        user = "root"
        host = "93.179.125.223:27196"
        pass = "TefmYnzGKFVa"
    [ide.storage]
        user = "root"
        host = "93.179.125.223:27196"
        pass = "TefmYnzGKFVa"
        workspaceBasePathRemote = "/mnt/code-platform"
        workspaceBasePathLocal = ""
# Database.
[database]
    link  = "mysql:root:12345678@tcp(localhost:3306)/scnu_coding"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true