// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// checkinRecordDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type checkinRecordDao struct {
	*internal.CheckinRecordDao
}

var (
	// CheckinRecord is globally public accessible object for table checkin_record operations.
	CheckinRecord checkinRecordDao
)

func init() {
	CheckinRecord = checkinRecordDao{
		internal.NewCheckinRecordDao(),
	}
}

// Fill with you ideas below.
