// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// checkinDetailDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type checkinDetailDao struct {
	*internal.CheckinDetailDao
}

var (
	// CheckinDetail is globally public accessible object for table checkin_detail operations.
	CheckinDetail checkinDetailDao
)

func init() {
	CheckinDetail = checkinDetailDao{
		internal.NewCheckinDetailDao(),
	}
}

// Fill with you ideas below.
