// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// codingTimeDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type codingTimeDao struct {
	*internal.CodingTimeDao
}

var (
	// CodingTime is globally public accessible object for table coding_time operations.
	CodingTime codingTimeDao
)

func init() {
	CodingTime = codingTimeDao{
		internal.NewCodingTimeDao(),
	}
}

// Fill with you ideas below.
