// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// courseCommentDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type courseCommentDao struct {
	*internal.CourseCommentDao
}

var (
	// CourseComment is globally public accessible object for table course_comment operations.
	CourseComment courseCommentDao
)

func init() {
	CourseComment = courseCommentDao{
		internal.NewCourseCommentDao(),
	}
}

// Fill with you ideas below.
