// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// courseAnnouncementDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type courseAnnouncementDao struct {
	*internal.CourseAnnouncementDao
}

var (
	// CourseAnnouncement is globally public accessible object for table course_announcement operations.
	CourseAnnouncement courseAnnouncementDao
)

func init() {
	CourseAnnouncement = courseAnnouncementDao{
		internal.NewCourseAnnouncementDao(),
	}
}

// Fill with you ideas below.
