// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// labDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type labDao struct {
	*internal.LabDao
}

var (
	// Lab is globally public accessible object for table lab operations.
	Lab labDao
)

func init() {
	Lab = labDao{
		internal.NewLabDao(),
	}
}

// Fill with you ideas below.
