// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// labSubmitDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type labSubmitDao struct {
	*internal.LabSubmitDao
}

var (
	// LabSubmit is globally public accessible object for table lab_submit operations.
	LabSubmit labSubmitDao
)

func init() {
	LabSubmit = labSubmitDao{
		internal.NewLabSubmitDao(),
	}
}

// Fill with you ideas below.
