// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// labCommentDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type labCommentDao struct {
	*internal.LabCommentDao
}

var (
	// LabComment is globally public accessible object for table lab_comment operations.
	LabComment labCommentDao
)

func init() {
	LabComment = labCommentDao{
		internal.NewLabCommentDao(),
	}
}

// Fill with you ideas below.
