// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// localFileDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type localFileDao struct {
	*internal.LocalFileDao
}

var (
	// LocalFile is globally public accessible object for table local_file operations.
	LocalFile = localFileDao{
		internal.NewLocalFileDao(),
	}
)

// Fill with you ideas below.