// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// messageNotifyDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type messageNotifyDao struct {
	*internal.MessageNotifyDao
}

var (
	// MessageNotify is globally public accessible object for table message_notify operations.
	MessageNotify messageNotifyDao
)

func init() {
	MessageNotify = messageNotifyDao{
		internal.NewMessageNotifyDao(),
	}
}

// Fill with you ideas below.
