// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// reApiRoleDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type reApiRoleDao struct {
	*internal.ReApiRoleDao
}

var (
	// ReApiRole is globally public accessible object for table re_api_role operations.
	ReApiRole reApiRoleDao
)

func init() {
	ReApiRole = reApiRoleDao{
		internal.NewReApiRoleDao(),
	}
}

// Fill with you ideas below.