// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"scnu-coding/app/dao/internal"
)

// reCourseUserDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type reCourseUserDao struct {
	*internal.ReCourseUserDao
}

var (
	// ReCourseUser is globally public accessible object for table re_course_user operations.
	ReCourseUser reCourseUserDao
)

func init() {
	ReCourseUser = reCourseUserDao{
		internal.NewReCourseUserDao(),
	}
}

// Fill with you ideas below.