// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package define

import (
	"github.com/gogf/gf/os/gtime"
	"github.com/gogf/gf/util/gmeta"
)

type UpdateReportContentReq struct {
	ReportContent string
	LabId         int
}

type GetReportContentAndCodeResp struct {
	ReportContent string
	Code          []*CodeData
}

type GetReportContentReq struct {
	UserId int
	LabId  int
}

type CodeData struct {
	Name      string      `json:"name"`      // 文件/文件夹名字
	Content   string      `json:"content"`   // 内容
	ChildNode []*CodeData `json:"childNode"` // 子节点
}

type ReadCodeDataReq struct {
	StuId int
	LabId int
}

type ListLabSubmitResp struct {
	gmeta.Meta `orm:"table:sys_user"`
	UserId     int `orm:"user_id" json:"userId"` // 用户id
	UserDetail *struct {
		gmeta.Meta `orm:"table:sys_user"`
		UserId     int    `orm:"user_id" json:"-"`         // 用户id
		Username   string `orm:"username" json:"username"` //
		UserNum    string `orm:"user_num" json:"userNum"`  // 学号
	} `orm:"with:user_id" json:"userDetail"`
	LabSubmitDetail struct {
		gmeta.Meta       `orm:"table:lab_submit"`
		LabSubmitId      int         `orm:"lab_submit_id" json:"labSubmitId"` //
		IsFinish         bool        `orm:"is_finish" json:"isFinish"`
		Score            int         `orm:"score" json:"score"`
		UserId           int         `orm:"user_id" json:"-"`
		LabSubmitComment string      `orm:"lab_submit_comment" json:"labSubmitComment"` // 评语
		UpdatedAt        *gtime.Time `orm:"updated_time" json:"updatedTime"`            // 更新时间
	} `json:"labSubmitDetail"`
	IsIDERunning bool `json:"isIDERunning"`
}

type ListLabSubmitIdResp struct {
	gmeta.Meta `orm:"table:sys_user"`
	UserId     int `orm:"user_id" json:"userId"` // 用户id
	UserDetail *struct {
		gmeta.Meta `orm:"table:sys_user"`
		UserId     int    `orm:"user_id" json:"-"`         // 用户id
		Username   string `orm:"username" json:"username"` //
		UserNum    string `orm:"user_num" json:"userNum"`  // 学号
	} `orm:"with:user_id" json:"userDetail"`
	LabSubmitDetail *struct {
		gmeta.Meta  `orm:"table:lab_submit"`
		LabSubmitId int `orm:"lab_submit_id" json:"labSubmitId"` //
		Score       int `orm:"score" json:"score"`
		UserId      int `orm:"user_id" json:"-"`
	} `json:"labSubmitDetail"`
}

//type LabSummitResp struct {
//	gmeta.Meta  `orm:"table:lab_submit"`
//	LabSubmitId int `orm:"lab_submit_id" json:"labSubmitId"` //
//	UserId      int `orm:"user_id" json:"userId"`            // 用户id
//	UserDetail  *struct {
//		gmeta.Meta `orm:"table:sys_user"`
//		UserId     int    `orm:"user_id" json:"userId"`    // 用户id
//		Username   string `orm:"username" json:"username"` //
//		UserNum    string `orm:"user_num" json:"userNum"`  // 学号
//	} `orm:"with:user_id" json:"userDetail"`
//	ReportUrl        string      `orm:"report_url" json:"reportUrl"`                // 存放实验报告pdf的url
//	FinishStat       int         `orm:"finish_stat" json:"finishStat"`              // 是否完成
//	Score            int         `orm:"score" json:"score"`                         // 分数
//	CodingTime       int         `json:"codingTime"`                                // 编码时间
//	LabSubmitComment string      `orm:"lab_submit_comment" json:"labSubmitComment"` // 评语
//	CreatedTime      *gtime.Time `orm:"created_time" json:"createdTime"`            // 创建时间
//	UpdatedTime      *gtime.Time `orm:"updated_time" json:"updatedTime"`            // 更新时间
//}

type UpdateLabSummitScoreAndCommentReq struct {
	UserId  int    // 用户id
	LabId   int    // 实验id
	Score   int    // 分数
	Comment string // 评语
}

type UpdateLabFinishReq struct {
	UserId   int
	IsFinish bool // 是否已经完成
	LabId    int
}

type ExportLabScore struct {
	gmeta.Meta       `orm:"table:lab"`
	LabId            int    `orm:"lab_id"`
	Title            string `orm:"title"` // 标题
	LabSubmitDetails []*struct {
		gmeta.Meta `orm:"table:lab_submit"`
		LabId      int  `orm:"lab_id"`
		Score      *int `orm:"score"`
		UserId     int  `orm:"user_id"`
	} `orm:"with:lab_id"`
}

type ExportLabScoreReq struct {
	CourseId int
	LabIds   []int
}
