// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// CodingTimeDao is the manager for logic model data accessing and custom defined data operations functions management.
type CodingTimeDao struct {
	Table   string          // Table is the underlying table name of the DAO.
	Group   string          // Group is the database configuration group name of current DAO.
	Columns CodingTimeColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// CodingTimeColumns defines and stores column names for table coding_time.
type CodingTimeColumns struct {
	CodingTimeId  string //                       
    LabId         string // 实验id                
    UserId        string // 学生id                
    Duration      string // 编码时间，分钟为单位  
    CreatedAt     string // 创建时间              
    UpdatedAt     string // 更新时间
}

//  codingTimeColumns holds the columns for table coding_time.
var codingTimeColumns = CodingTimeColumns{
	CodingTimeId: "coding_time_id",  
            LabId:        "lab_id",          
            UserId:       "user_id",         
            Duration:     "duration",        
            CreatedAt:    "created_at",      
            UpdatedAt:    "updated_at",
}

// NewCodingTimeDao creates and returns a new DAO object for table data access.
func NewCodingTimeDao() *CodingTimeDao {
	return &CodingTimeDao{
		Group:   "default",
		Table:   "coding_time",
		Columns: codingTimeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CodingTimeDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CodingTimeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CodingTimeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}